# Site settings
title: Yin Haomin's Blog
SEOTitle: 殷浩民的博客 | Yin Haomin's Blog
header-img: img/home-bg.jpg
tagline: ''
sidebar_image: /images/checker.jpg
lang: 'zh-cmn-Hans'
url: http://www.yinhaomin.com/
author: Yin Haomin
plus: https://www.facebook.com/dave.yi.3

# Build settings
markdown: kramdown
highlighter: rouge
baseurl: # the subpath of your site, e.g. /blog/

permalink:   /:categories/:title/
paginate: 8
paginate_path: "/page:num/"

highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

# Duoshuo settings
duoshuo_username: HaominYin
# Share component is depend on Comment so we can NOT use share only.
# duoshuo_share: true                     # set to false if you want to use Comment without Sharing


