# Site settings
title: Yin Haomin's Blog
tagline: ''
sidebar_image: /images/checker.jpg
lang: 'zh-cmn-Hans'
url: http://www.yinhaomin.com/
author: Wenhao Ji
plus: https://www.facebook.com/dave.yi.3

# Build settings
markdown: kramdown
highlighter: rouge
baseurl: # the subpath of your site, e.g. /blog/

permalink:   /:categories/:title/

paginate: 2

